# Generated by Django 4.1.3 on 2023-01-30 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id_person', models.TextField(primary_key=True, serialize=False, unique=True)),
                ('first_name', models.TextField()),
                ('second_name', models.TextField()),
                ('city', models.TextField()),
                ('country', models.TextField()),
                ('education', models.TextField()),
                ('occupation', models.TextField()),
                ('family', models.TextField()),
                ('birthday', models.TextField()),
                ('alcohol', models.TextField()),
                ('smoke', models.TextField()),
                ('political', models.TextField()),
                ('interests', models.TextField()),
            ],
            options={
                'verbose_name': 'Персона',
                'verbose_name_plural': 'Персоны',
                'db_table': 'persons',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id_post', models.TextField(primary_key=True, serialize=False, unique=True)),
                ('post_text', models.TextField()),
                ('post_ref', models.TextField()),
                ('time_check_first', models.IntegerField()),
                ('time_last_comment', models.IntegerField()),
                ('post_date', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'db_table': 'posts',
            },
        ),
        migrations.CreateModel(
            name='Toxic_Post',
            fields=[
                ('id_post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.post')),
                ('toxic', models.FloatField()),
                ('count', models.BooleanField()),
                ('number', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Токсичный пост',
                'verbose_name_plural': 'Токсичные посты',
                'db_table': 'toxic_posts',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id_comment', models.TextField(primary_key=True, serialize=False, unique=True)),
                ('comment', models.TextField()),
                ('comment_date', models.IntegerField()),
                ('id_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.person')),
                ('id_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.post')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'db_table': 'comments',
            },
        ),
        migrations.CreateModel(
            name='Toxic_Comment',
            fields=[
                ('id_comment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.comment')),
                ('toxic', models.FloatField()),
                ('id_post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.post')),
            ],
            options={
                'verbose_name': 'Токсичный комментарий',
                'verbose_name_plural': 'Токсичные комментарии',
                'db_table': 'toxic_comments',
            },
        ),
    ]
